### PR TITLE
Update python version to 3.7.5 for win64 and linux

### PR DESCRIPTION
**Pull request by DartBond**

### CODE REVIEW

**Comment by historybuffjb** [comment]
Is this going to get merged in?

**Comment by cdrx** [comment]
Not as it is, no.

All the images should have consistent Python & PyInstaller versions. Read me would need adjusting also.

**Comment by historybuffjb** [comment]
@DartBond anyway you could finish up these changes? If not maybe I could submit my own PR?

**Comment by DartBond** [comment]
@historybuffjb, please create your own PR (I don't have free time)?

**Pull request closed without merging**
